/**
 * Constants Index
 * Centralized export of all constants
 */

const { API_ROUTES, FULL_ROUTES } = require("./apiRoutes");
const {
  OTP_CHANNEL,
  HIT_TYPE,
  LOGIN_TYPE,
  LOGIN_VIA,
  GENDER,
  USER_STATUS,
  ACCOUNT_STATUS,
  DELETION_TYPE,
  DELETION_STATUS,
  QR_ID_STATUS,
  VERIFICATION_STATUS,
  TRACKING_STATUS,
  NOTIFICATION_TYPE,
  VEHICLE_CLASS,
  FUEL_TYPE,
  INSURANCE_TYPE,
  RC_STATUS,
  HTTP_STATUS,
  RESPONSE_STATUS,
  OTP_CONFIG,
  PASSWORD_CONFIG,
  JWT_CONFIG,
  HIT_BY,
  DEVICE_HIT_TYPE,
  FILE_UPLOAD_TYPE,
  DOCUMENT_TYPE,
  FILE_STATUS,
  UPLOAD_FOLDER,
  VALIDATION_RULES,
} = require("./enums");
const {
  SUCCESS_MESSAGES,
  ERROR_MESSAGES,
  INFO_MESSAGES,
  VALIDATION_MESSAGES,
} = require("./messages");

module.exports = {
  // Routes
  API_ROUTES,
  FULL_ROUTES,

  // Enums
  OTP_CHANNEL,
  HIT_TYPE,
  LOGIN_TYPE,
  LOGIN_VIA,
  GENDER,
  USER_STATUS,
  ACCOUNT_STATUS,
  DELETION_TYPE,
  DELETION_STATUS,
  QR_ID_STATUS,
  VERIFICATION_STATUS,
  TRACKING_STATUS,
  NOTIFICATION_TYPE,
  VEHICLE_CLASS,
  FUEL_TYPE,
  INSURANCE_TYPE,
  RC_STATUS,
  HTTP_STATUS,
  RESPONSE_STATUS,
  OTP_CONFIG,
  PASSWORD_CONFIG,
  JWT_CONFIG,
  HIT_BY,
  DEVICE_HIT_TYPE,
  FILE_UPLOAD_TYPE,
  DOCUMENT_TYPE,
  FILE_STATUS,
  UPLOAD_FOLDER,
  VALIDATION_RULES,

  // Messages
  SUCCESS_MESSAGES,
  ERROR_MESSAGES,
  INFO_MESSAGES,
  VALIDATION_MESSAGES,
};
